export const mockStaffMembers = [
  { id: "principal", name: "Dr. K. Sridharan", dept: "Principal", password: "jkkmct" },
  { id: "cse001", name: "Dr. N. Sathyabalaji", dept: "CSE", password: "jkkmct" },
  { id: "cse002", name: "Mr. E. Ananth", dept: "CSE", password: "jkkmct" },
  { id: "cse003", name: "Mrs. P. Poornapriya", dept: "CSE", password: "jkkmct" },
  { id: "cse004", name: "Mrs. M. C. Savithri", dept: "CSE", password: "jkkmct" },
  { id: "cse005", name: "Mrs. L. Dharani", dept: "CSE", password: "jkkmct" },
  { id: "cse006", name: "Mr. G. Tamilselvan", dept: "CSE", password: "jkkmct" },
  { id: "it001", name: "Mr. S. Pradeepan", dept: "IT", password: "jkkmct" },
  { id: "it002", name: "Mrs. M. Sathiyapriya", dept: "IT", password: "jkkmct" },
  { id: "it003", name: "Mrs. N. Dhanalakshmi", dept: "IT", password: "jkkmct" },
  { id: "mca001", name: "Mrs. L. Karthika", dept: "MCA", password: "jkkmct" },
  { id: "mca002", name: "Mrs. R. Vanithamani", dept: "MCA", password: "jkkmct" },
  { id: "mca003", name: "Ms. P. Sureka", dept: "MCA", password: "jkkmct" },
  { id: "admin001", name: "Mr. K. Sakthivel", dept: "Admin", password: "jkkmct" },
  { id: "cse007", name: "Mrs. R. Vakitha Banu", dept: "CSE", password: "jkkmct" },
  { id: "cse008", name: "Ms. A. Jeevakavi", dept: "CSE", password: "jkkmct" },
  { id: "cse009", name: "Mr. K. Hariprakash", dept: "CSE", password: "jkkmct" },
  { id: "it004", name: "Mr. S. Muruga Shankar", dept: "IT", password: "jkkmct" },
  { id: "it005", name: "Mr. E. Vijayananth", dept: "IT", password: "jkkmct" },
  { id: "mca004", name: "Mr. I. Manikandan", dept: "MCA", password: "jkkmct" },
  { id: "cse010", name: "Mr. I. Surya", dept: "CSE", password: "jkkmct" },
  { id: "ad001", name: "Mrs. D. Nivethini", dept: "AI&DS", password: "jkkmct" },
  { id: "ad002", name: "Mrs. K. Poornima", dept: "AI&DS", password: "jkkmct" },
  { id: "ad003", name: "Mrs. S. Anbumalar", dept: "AI&DS", password: "jkkmct" },
  { id: "ad003a", name: "Mr. N. Madhesh", dept: "AI&DS", password: "jkkmct" },
  { id: "ad004", name: "Mr. M. Poornachandran", dept: "AI&DS", password: "jkkmct" },
  { id: "ad005", name: "Mrs. V. S. Vasuki", dept: "AI&DS", password: "jkkmct" },
  { id: "ad006", name: "Mr. K. S. Naveen Kumar", dept: "AI&DS", password: "jkkmct" },
  { id: "cs001", name: "Dr. S. B. Manooj kumaar", dept: "Cyber Security", password: "jkkmct" },
  { id: "cs002", name: "Mr. M. Renukadevi", dept: "Cyber Security", password: "jkkmct" },
  { id: "cs003", name: "Mr. P. Suganthi", dept: "Cyber Security", password: "jkkmct" },
  { id: "cs004", name: "Mr. N. Adhiseshan", dept: "Cyber Security", password: "jkkmct" },
  { id: "auto001", name: "Mr. V. Magesh", dept: "Automobile", password: "jkkmct" },
  { id: "auto002", name: "Mr. V. P. Arulmurugan", dept: "Automobile", password: "jkkmct" },
  { id: "auto003", name: "Mr. S. Ganesh kumar", dept: "Automobile", password: "jkkmct" },
  { id: "auto004", name: "Mr. K. Magesh", dept: "Automobile", password: "jkkmct" },
  { id: "auto005", name: "Mr. R. Rajkumar", dept: "Automobile", password: "jkkmct" },
  { id: "civil001", name: "Mrs. V. Mohanapriya", dept: "Civil", password: "jkkmct" },
  { id: "civil002", name: "Ms. V. Sathiyapriya", dept: "Civil", password: "jkkmct" },
  { id: "civil003", name: "Mrs. P. Reena", dept: "Civil", password: "jkkmct" },
  { id: "civil004", name: "Mr. G. Ruthish kumar", dept: "Civil", password: "jkkmct" },
  { id: "civil005", name: "Mr. R. Venkatesh", dept: "Civil", password: "jkkmct" },
  { id: "ece001", name: "Mr. A. Vigneshkumar", dept: "ECE", password: "jkkmct" },
  { id: "ece002", name: "Mrs. U. Sasikala", dept: "ECE", password: "jkkmct" },
  { id: "ece003", name: "Mrs. N. Gomathi", dept: "ECE", password: "jkkmct" },
  { id: "ece004", name: "Mrs. R. Kokila", dept: "ECE", password: "jkkmct" },
  { id: "ece005", name: "Mrs. M. Sivaranjani", dept: "ECE", password: "jkkmct" },
  { id: "ece006", name: "Mrs. C. Gayathri", dept: "ECE", password: "jkkmct" },
  { id: "ece007", name: "Mrs. S. Divya", dept: "ECE", password: "jkkmct" },
  { id: "ece008", name: "Mrs. P. Kawya", dept: "ECE", password: "jkkmct" },
  { id: "lab001", name: "Mrs. M. Anusuya", dept: "ECE", password: "jkkmct" },
  { id: "ece009", name: "Mr. P. Sasikumar", dept: "ECE", password: "jkkmct" },
  { id: "ece010", name: "Ms. D. Sangeetha", dept: "ECE", password: "jkkmct" },
  { id: "eee001", name: "Dr. C. Saravanan", dept: "EEE", password: "jkkmct" },
  { id: "eee002", name: "Mr. S. M. Pranesh", dept: "EEE", password: "jkkmct" },
  { id: "eee003", name: "Mr. T. S. Thambiran", dept: "EEE", password: "jkkmct" },
  { id: "eee004", name: "Mr. G. Palanisamy", dept: "EEE", password: "jkkmct" },
  { id: "eee005", name: "Mr. S. Srinivasan", dept: "EEE", password: "jkkmct" },
  { id: "eee006", name: "Ms. M. Mohanambika", dept: "EEE", password: "jkkmct" },
  { id: "eee007", name: "Mrs. N. Mekala", dept: "EEE", password: "jkkmct" },
  { id: "lab002", name: "Mr. B. Balaji", dept: "EEE", password: "jkkmct" },
  { id: "mech001", name: "Dr. N. Sankar", dept: "Mech", password: "jkkmct" },
  { id: "mech002", name: "Mr. K. S. Ramesh", dept: "Mech", password: "jkkmct" },
  { id: "mech003", name: "Mr. S. Karthikeyan", dept: "Mech", password: "jkkmct" },
  { id: "mech004", name: "Mr. E. Deeparaj", dept: "Mech", password: "jkkmct" },
  { id: "mech005", name: "Mr. P. Eswaran", dept: "Mech", password: "jkkmct" },
  { id: "mech006", name: "Mr. M. Sivakumar", dept: "Mech", password: "jkkmct" },
  { id: "mech007", name: "Mr. K. Ganeshan", dept: "Mech", password: "jkkmct" },
  { id: "s&h001", name: "Ms. S. Poornima", dept: "S&H", password: "jkkmct" },
  { id: "s&h002", name: "Ms. M. Kavitha", dept: "S&H", password: "jkkmct" },
  { id: "s&h003", name: "Mr. M. Ponnusamy", dept: "S&H", password: "jkkmct" },
  { id: "s&h004", name: "Mr. P. Velusamy", dept: "S&H", password: "jkkmct" },
  { id: "s&h005", name: "Ms. M. Senbagam", dept: "S&H", password: "jkkmct" },
  { id: "s&h006", name: "Mr. P. Ramesh", dept: "S&H", password: "jkkmct" },
  { id: "s&h007", name: "Mr. E. Mathivanan", dept: "S&H", password: "jkkmct" },
  { id: "s&h007a", name: "Ms. K. Ranjitha", dept: "S&H", password: "jkkmct" },
  { id: "s&h008", name: "Ms. P. Jemimma", dept: "S&H", password: "jkkmct" },
  { id: "s&h009", name: "Ms. P. Shanthi", dept: "S&H", password: "jkkmct" },
  { id: "s&h010", name: "Ms. S. Samyuktha", dept: "S&H", password: "jkkmct" },
  { id: "s&h011", name: "Ms. M. Rajathi", dept: "S&H", password: "jkkmct" },
  { id: "s&h012", name: "Ms. P. Manjubashini", dept: "S&H", password: "jkkmct" },
  { id: "s&h012a", name: "Mr. S. Sneha", dept: "S&H", password: "jkkmct" },
  { id: "s&h013", name: "Ms. S. Sathiya", dept: "S&H", password: "jkkmct" },
  { id: "s&h014", name: "Ms. A. K. Sowmiya", dept: "S&H", password: "jkkmct" },
  { id: "s&h014a", name: "Mr. Balakrishnan", dept: "S&H", password: "jkkmct" },
  { id: "s&h015", name: "Mrs. R. Sasirekha", dept: "S&H", password: "jkkmct" },
  { id: "s&h016", name: "Mr. P. Kavitha", dept: "S&H", password: "jkkmct" },
  { id: "s&h017", name: "Dr. M. Vijayrakavan", dept: "S&H", password: "jkkmct" },
  { id: "s&h018", name: "Mr. R. Chitra", dept: "S&H", password: "jkkmct" },
  { id: "s&h019", name: "Mr. Mohanraj", dept: "S&H", password: "jkkmct" },
  { id: "coe001", name: "Mrs. A. Sumathi", dept: "COE", password: "jkkmct" },
  { id: "coe002", name: "Mr. K. M. Sathish", dept: "COE", password: "jkkmct" },
  { id: "coe003", name: "Ms. S. Janupriya", dept: "COE", password: "jkkmct" },
  { id: "coe004", name: "Mrs. D. Yamuna", dept: "COE", password: "jkkmct" },
  { id: "coe005", name: "Ms. B. Lakshmi Prabha", dept: "COE", password: "jkkmct" },
  { id: "ec001", name: "Mrs. K. Padmini", dept: "Exam Cell", password: "jkkmct" },
  { id: "ec002", name: "Ms. S. Desika", dept: "Exam Cell", password: "jkkmct" },
  { id: "ec003", name: "Mrs. M. Jayananthini", dept: "Exam Cell", password: "jkkmct" },
  { id: "ec004", name: "Ms. G. K. B. Yazheni", dept: "Exam Cell", password: "jkkmct" },
  { id: "lib001", name: "Mrs. K. Reka", dept: "Library", password: "jkkmct" },
  { id: "lib002", name: "Dr. N. Sundareswaran", dept: "Library", password: "jkkmct" },
  { id: "pc001", name: "Ms. D. S. Thrinethraa", dept: "Placement", password: "jkkmct" },
  { id: "pc002", name: "Ms. M. Sunmathi", dept: "Placement", password: "jkkmct" },
  { id: "pc003", name: "Ms. S. Naveena", dept: "Placement", password: "jkkmct" },
  { id: "pc004", name: "Ms. K. Kiruthika", dept: "Placement", password: "jkkmct" },
  { id: "ac001", name: "Mr. B. Dinesh Babu", dept: "Admission", password: "jkkmct" },
  { id: "ac002", name: "Ms. V. Deepa", dept: "Admission", password: "jkkmct" },
  { id: "office001", name: "Mr. S. Ravikumar", dept: "Office", password: "jkkmct" },
  { id: "office002", name: "Mr. S. Keerthana", dept: "Office", password: "jkkmct" },
  { id: "office003", name: "Mr. S. Gowrisankar", dept: "Office", password: "jkkmct" },
  { id: "office004", name: "Mr. L. Alagesan", dept: "Office", password: "jkkmct" },
  { id: "office005", name: "Mr. S. Sachithananthan", dept: "Office", password: "jkkmct" },
  { id: "office006", name: "Mrs. Kalaivani", dept: "Office", password: "jkkmct" },
  { id: "office007", name: "Mr. Samayamuthu", dept: "Office", password: "jkkmct" },
  { id: "office008", name: "Mr. K. Thangaraju", dept: "Office", password: "jkkmct" },
  { id: "office009", name: "Mr. G. Alagar", dept: "Office", password: "jkkmct" },
  { id: "office010", name: "Mr. K. Manoharan", dept: "Office", password: "jkkmct" },
  { id: "office011", name: "Mr. S. Ramprabhu", dept: "Office", password: "jkkmct" },
  { id: "office012", name: "Mrs. T. Shandhi", dept: "Office", password: "jkkmct" },
  { id: "mba001", name: "Dr. E. R. Vadivel", dept: "MBA", password: "jkkmct" },
  { id: "mba002", name: "Mr. R. Prasanth", dept: "MBA", password: "jkkmct" },
  { id: "mba003", name: "Mr. B. Sivakumar", dept: "MBA", password: "jkkmct" },
  { id: "yoga001", name: "Mrs. Sangeetha", dept: "Yoga", password: "jkkmct" },
  { id: "pd001", name: "Mr. Murugesan", dept: "PD", password: "jkkmct" },
  { id: "pd002", name: "Mr. A. Srinivasan", dept: "PD", password: "jkkmct" },
  { id: "pd003", name: "Mr. R. Velmurugan", dept: "PD", password: "jkkmct" },
  { id: "pd004", name: "Mr. S. Parivendhan", dept: "PD", password: "jkkmct" },
  { id: "fm001", name: "Ms. Arthi", dept: "FM Radio", password: "jkkmct" }
];

export const ADMIN_CREDENTIALS = {
  id: "admin",
  password: "admin"
};
